### ISSUE TITLE
what would you think about changing the license from GPL3 to MIT?

### ISSUE THREAD

**Issue by lebouquetin** [jucacrispim/mongomotor#6]
Hi @jucacrispim ,

I'm working on a large project involving MongoDB and MongoEngine. We are about to refactor our code in order to make Mongo queries asynchronous. mongomotor is the solution to our problem and we are almost about to integrate it in our project.

The project is a professionnal project, this means that we would report bugs, propose pull requests, etc. We would be contributors to your project.

Unfortunately, our project is distributed under a proprietary licence, which is not compatible with GPL 3 - the licence of mongomotor.

Question : would you mind changing mongomotor's license from GPL 3 to something like Apache or MIT?

I ask the question because you may have chosen GPL 3 ...

- for strong reasons (like you do not want mongomotor to be included in proprietary software) 
- "as a default choice" because you did not know which open source licence to choose and GPL 3 sounded like a good choice but are not against changing it.

Let me know your point of view. We'll decide to continue with mongomotor if changing the licence is ok for you, or we'll continue our investigations in order to find the right module for our needs.

Damien

**Comment by jucacrispim** [comment]
Hello @lebouquetin !

I'm glad for your interest, but the thing is that I'm using GPLv3 because I like the idea of copyleft licenses. 

When I first released mongomotor - and now - I've thought about using a more permissive license because new users and contributors are really needed and welcome, but I would not feel good with myself changing mongomotor's license because I want more people here, you know?

So, I'm sorry, but I'm not gonna change the license for a more permissive one.

**Comment by lebouquetin** [comment]
Hello @jucacrispim 

Thanks for your answer. Sad to read your answer but it's ok - it's your code after all ;)
We'll look for another tool - answering to our needs.

Damien
